/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_semes_test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Wissem
 */
public class table_stockage extends javax.swing.JFrame {

    /**
     * Creates new form table_stockage
     */
    public table_stockage() {
        initComponents();
        this.setIconImage(new ImageIcon("./src/images/table.gif").getImage());
        int i=1;
        
        
           try{
                String ip = null;
	Class.forName("com.mysql.jdbc.Driver").newInstance();
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/SNMP","root","");
	
	Statement stat = con.createStatement();
        ResultSet rs = stat.executeQuery("select val from ip");
      
         while(rs.previous()){}
         
         while (rs.next()) {
        ip=rs.getString(1);
         }
        
        
        while(!new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i).equals("Null")){
            //jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.3.2.1.3."+k) , i-1, 0); 
            if(i<3){
            int un = Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.4."+i));
            int ut = (Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.6."+i))/un)*10;
            int lib= (Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i))/un)*10;
            jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.3."+i) , i-1, 0);//desc
            jTable1.setValueAt(un , i-1, 1);//unit stock
            jTable1.setValueAt( ut+lib, i-1, 2);//totale
            jTable1.setValueAt( ut, i-1, 3);//utilisé
            jTable1.setValueAt( lib, i-1, 4);//libre
            
            }
           /* else if(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.3."+i).equals("Virtual Memory")||new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.3."+i).equals("Physical Memory")){
                int unit =Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.4."+i));
                jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.3."+i) , i-1, 0);
                jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.4."+i) , i-1, 1);
                jTable1.setValueAt(Integer.parseInt((new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i))+Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.6."+i)))/unit , i-1, 2);
                jTable1.setValueAt((Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i)))/unit , i-1, 3);
                jTable1.setValueAt((Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.6."+i)))/unit  , i-1, 4);
            }*/
            else{
              jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.3."+i) , i-1, 0);
                jTable1.setValueAt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.4."+i) , i-1, 1);
                jTable1.setValueAt(Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i))+Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.6."+i)) , i-1, 2);
                jTable1.setValueAt(Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.5."+i)) , i-1, 3);
                jTable1.setValueAt(Integer.parseInt(new OID_info().recherche(ip,"1.3.6.1.2.1.25.2.3.1.6."+i)), i-1, 4);  
            }
        
        i++;
        
        }
    }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Description", "Unité d'allocation(Octets)", "Taille totale(MB)", "Espace utilisé(MB)", "Espace Libre(MB)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 191));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table_stockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table_stockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table_stockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table_stockage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table_stockage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
